config/routes.rb
Jebretary::Application.routes.draw do
  get "welcome/index"
  get "welcome/edit"
  post "welcome/update"
  match "instances/:id/update" => "instances#update"

  resources :subassemblies
  resources :launch
  resources :transfer
  resources :messages
  
  resources :campaigns do
    resources :saves
  end
  resources :saves  
  resources :crafts
  resources :instances

  match "settings" => "welcome#settings"  
  match "new_version_info" => "welcome#new_version_info"
  match "reset_cache" => "application#cache_reset"

  root :to => 'welcome#index'

end

app/models/craft.rb
class Craft < ActiveRecord::Base
  include CommitMessageChanger
  include RepoObject
  include CommonLogic
  include Transferable

  attr_accessible :name, :craft_type, :deleted, :part_count, :history_count, :last_commit, :commit_messages, :part_data, :sync
  belongs_to :campaign

  require 'active_support/builder'

  validates :commit_messages, :git_compatible => true


  #retun the path to the .craft file, form the root of the repo.
  def local_path
    "Ships/#{craft_type.upcase}/#{name}.craft"
  end
  alias file_name local_path 


  def parts args = {:load_data => false, :read_file => true}
    @parts = nil if args[:load_data]
    return @parts if defined?(@parts) && !@parts.nil?
    @parts = CraftFileReader.new(self, args)
  end

  def update_part_data
    return false if self.deleted?
    parts.locate_in self.crafts_campaign.campaigns_instance.parts
    data = {:parts => parts.found, :missing_parts => parts.missing, :stock => parts.stock?, :mods => parts.mods}
    self.part_data = data
    true
  end  

  def part_data
    data = super
    data = JSON.parse(data) unless data.blank?
    data ||= {}
    HashWithIndifferentAccess.new(data)
  end

  def part_data= data
    data = data.to_json unless data.nil?
    super(data)
  end

  alias new_craft? is_new?
  alias changed_craft? is_changed?

  
  def dont_process_campaign_while &blk
    self.campaign.update_attributes(:persistence_checksum => "skip") #unless self.campaign.persistence_checksum.eql?("skip")
    yield
    self.campaign.update_persistence_checksum
  end


  #stage the changes and commits the craft. simply returns if there are no changes.
  def commit args = {}
    action = :deleted if self.deleted?
    action ||= self.is_new? ? :added : (self.is_changed? ? :updated : :nothing_to_commit)     
    args[:skip_part_data] ||= false
    
    unless action.eql?(:nothing_to_commit)
      message = "#{action} #{name}"
      message = args[:m] if args[:m]      
      if action.eql?(:deleted)
        repo.remove(self.file_name)
        self.history_count += 1
      else
        repo.add(self.file_name)
      end

      active_message = self.commit_messages[:most_recent]
      message = "#{active_message.gsub(message,"")}" unless self.deleted? || active_message.blank? || active_message.eql?(message)
      self.remove_message_from_temp_store(:most_recent) unless active_message.blank?
      
      repo.commit(message)
      self.last_commit = repo.log(self.local_path, :limit => 1).first.to_s
    end
    unless action.eql?(:deleted)    
      self.part_count = parts.count
      self.part_count ||= 0      
      update_part_data unless args[:skip_part_data]

      self.history_count = self.history.size
      self.history_count = 1 if self.history_count.eql?(0)        
    end
    self.save if self.changed?
  
    synchronize unless args[:dont_sync] || self.attributes["sync"].blank? #rather than calling sync.blank? to skip the JSON parsing step.
    return action
  end

  def replace_most_recent_key_with_latest_commit_sha
    msgs = commit_messages
    return unless msgs.has_key?("most_recent")
    m = msgs["most_recent"]
    msgs.delete("most_recent")
    msgs[history(:linit => 1).first] = m
    self.commit_messages = msgs
    self.save
  end


end

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController

  respond_to :html, :js

  def index
    #raise params.inspect
    respond_with(@craft) do |f|      
      f.js { 
        unless params[:search_for].empty?
          if params[:search_for].eql?("*.*") || params[:search_for].eql?("*all")
            @craft = Craft.all
            @subs = Subassembly.all if params[:include_subs]
          else
            @craft = Craft.where("LOWER(name) LIKE :query", {:query => "%#{params[:search_for].downcase}%"}) 
            @subs = Subassembly.where("LOWER(name) LIKE :query", {:query => "%#{params[:search_for].downcase}%"}) if params[:include_subs]
          end
        else
          @craft = nil
        end
      }
    end    
  end

  def show
    respond_with(@craft) do |f|
      f.html{
        Rails.cache.delete("state_stamp")
        @craft = Craft.find(params[:id])       
        unless @craft.deleted?
          @craft.update_part_data 
          @craft.save if @craft.changed?
          @parts = @craft.parts :load_data => true, :read_file => false
          @part_for_list = @parts.found.group_by{|part| part[:name]}.to_a.sort_by{|part| part[1][0][:mod].downcase}.map{|p| [p[0], p[1].sort_by{|pt| pt[:name].downcase} ] }.in_groups(2)      
        end        
      }
      f.js{
        if params[:open_part_folder]
          @craft = Craft.find(params[:id])
          path = File.join([@craft.campaign.instance.path, params[:open_part_folder]])

          if path.match(/.cfg$/)
            path = path.split("/")
            path.pop
            path = File.join(path)
          end

          begin 
            if RUBY_PLATFORM =~ /mswin|mingw|cygwin/
              `start explorer.exe #{path.split("/").join("\\")}` #this has to be in windows format which is not what File.join returns 
            else
              `nautilus #{path}`
            end
          rescue
          end
          return render :text => "done"

        else

          ensure_no_db_lock do         
            @craft = Craft.find(params[:id])
            campaign = @craft.campaign

            state = [campaign.repo.log(:limit => 1).first.to_s, campaign.has_untracked_changes?].to_json
            state = Digest::SHA256.hexdigest(state)

            if Rails.cache.read("state_stamp") != state || !Rails.cache.read("last_controller").eql?("CraftsController") 
              @history = @craft.history  
              @sync_targets = @craft.sync_targets
            else
              return render :partial => "partials/no_update"
            end
            Rails.cache.write("state_stamp", state)

          end
        end
      }
    end
  end

  def edit
    @craft = Craft.find(params[:id])
    respond_with(@craft) do |f|
      f.html{        
        @sha_id = params[:sha_id]
        history = @craft.history
        @commit = history.select{|c| c.to_s.eql?(@sha_id)}.first
        @is_changed = @craft.is_changed?
        
        unless @craft.deleted?          
          @revert_to_version = history.reverse.map{|h| h.sha_id}.index(@sha_id) + 1
          @current_version = @craft.history_count
        end
        @latest_commit = history.first
        @return_to = params[:return_to]       
      }
      f.js {
        
      
      }
    end
  end

  def update
    @craft = Craft.find(params[:id])
    @campaign = @craft.campaign

    if params[:revert_craft]
      @craft.revert_to params[:sha_id], :commit => params[:commit_revert].eql?("true") 
      message = "Your craft has been reverted.</br>Reload it in the KSP editor"
    end
    if @craft.deleted? && params[:recover_deleted]
      message = "Your craft has been recovered.</br>You can now load it in KSP"
      @craft.recover 
    end

    if params[:force_commit]
      @craft.commit :m => @craft.commit_messages["most_recent"]
      @craft.remove_message_from_temp_store "most_recent"
      @craft.save
    end

    respond_with(@craft) do |f|
      f.html{        
        if params[:return_to] && params[:return_to] == "campaign"
          redirect_to @campaign, :notice => message.html_safe
        else
          redirect_to @craft, :notice => message.html_safe
        end
      }
    end
  end

  def destroy
    @craft = Craft.find(params[:id])
    notice = @craft.delete_file
    redirect_to @craft.campaign, :notice => notice
  end
end

app/views/crafts/_craft_list.html.haml
-unless campaign.blank?
  :javascript
    auto_switch_display_based_on("#{most_recent_commit}");
    auto_show_deleted_craft_link("#{deleted_craft_count}")



  #content_for_campaign_saves.hidden
    .grid_8.alpha
      %h3 Saves
      = link_to "view full save history", campaign_saves_path(campaign)

    .clear
    .grid_6.alpha
      #quicksave_display
        .left.label= "Quicksaves |"
        .left= link_to_function "Persistent", "toggle_save_display()"
        .clear
        #quicksave_partial
          = render "saves/short_list", :saves => saves, :save_type => "quicksave", :campaign => campaign, :has_change => campaign.changed_save?("quicksave", repo), :campaign_commit_messages => campaign_commit_messages

      #persistent_display.hidden
        .left= link_to_function "Quicksaves", "toggle_save_display()"
        .left.label= "| Persistent"
        .clear
        #persistent_partial
          = render "saves/short_list", :saves => saves, :save_type => "persistent", :campaign => campaign, :has_change => campaign.changed_save?("persistent", repo), :campaign_commit_messages => campaign_commit_messages


  .clear
  #content_for_current_project.hidden
    - unless current_project.nil?
      %h3 Current Project
      .craft
        .name= link_to(current_project.name, craft_path(current_project))
        .clear
        -if new_and_changed[:new].include?("Ships/#{current_project.craft_type.upcase}/#{current_project.name}.craft")
          = "new"
        -else
          - changed = new_and_changed[:changed].include?("Ships/#{current_project.craft_type.upcase}/#{current_project.name}.craft")
          .left
            .left= "Number of versions: #{current_project.history_count}"
            .left.with_margin.small.aligned
              -if changed
                .untracked= " + untracked recent changes"
              -else
                = "(No new changes)"

          - if changed
            .left.with_margin
              = form_for(current_project, :remote => true) do |f|
                = hidden_field_tag :force_commit, true
                = f.submit "Commit (save) Now!"

          .clear
          - version = current_project.history_count
          - version ||= 1
          //- unless version.eql?(1)
          .left Revert to Previous Version:
          .left.with_margin
            - n = changed ? 0 : 1
            - recent_history = current_project_history[n..(n+2)]
            - version += 1 if changed
            - unless recent_history.nil?
              - recent_history.each_with_index do |prev_version, index|
                = link_to "V#{version -= 1}", {:controller => "crafts", :action => "edit", :id => current_project.id, :sha_id => prev_version.sha_id, :return_to => :campaign}, :title => prev_version.message
                -unless prev_version == recent_history.last
                  |
          .left
            - if current_project_history.size > 4
              |
              = link_to "more", craft_path(current_project)
            = "|" unless current_project_history.size.eql?(1) && !changed
            = link_to_function "info", "show_current_project_help(#{current_project_history.size})"
          .clear
          .message
            - commit = current_project_history.first
            - if commit

              - commit = "most_recent" if changed
              - message = current_project_commit_messages[commit.to_s]
              - message ||= commit.message unless changed

              -if changed && current_project_commit_messages[commit.to_s].blank?
                %h4
                  %a{:onclick => "change_message(this, '#{message}', #{current_project.id}, '#{commit.to_s}')", :href => '#'}
                    Click to Add Notes:
              -else
                .message_text{:onclick => "change_message(this, '#{message}', #{current_project.id}, '#{commit.to_s}')"}
                  - message.split("<br>").each do |m|
                    .small= m
                  .small.label= "click text to edit"
              .message_form{:id => "message_form_for_#{commit.to_s}", :class => (changed ? "with_untracked_changes" : "")}

    - else
      %h3 No Current Project Defined
      %h5 what you looking at me for, Go Build something!


  .clear
  #content_for_subassemblies
    - if subassemblies.empty?
      .centered
        %h3 You don't have any Subassemblies in this Campaign
      
    - subassemblies.each do |sub|
      .subassembly{:id => "subassembly_#{sub.id}", :class => sub.deleted? ? "deleted_craft" : ""}
        .name= link_to sub.name.truncate(35), subassembly_path(sub)
        .history
          -unless sub.deleted?
            = "#{sub.history_count} version#{sub.history_count.eql?(1) ? '' : 's'}" unless sub.history_count.nil?
          -else
            = "deleted"
        .sub_container
        
    
  
  - craft_for_list.each do |type, crafts|
    %div{:id => "content_for_#{type}_list"}
      - unless crafts.blank?
        - crafts.each do |craft|
          -# next if craft.eql?(current_project)
          - part_data = craft.part_data
          - craft.crafts_campaign = campaign
          - klass = ""
          - klass << (part_data[:stock] ? "stock_craft" : "mod_craft") unless part_data.empty?
          - klass << " missing_parts" if part_data[:missing_parts] && !part_data[:missing_parts].empty?
          - klass << " deleted_craft" if craft.deleted?
          .craft_container{:class => klass}
            .craft
              .error= "!!"
              .name= truncated_link_to craft.name, craft_path(craft)
              .clear
              .git_info
                - unless craft.deleted?
                  -if new_and_changed[:new].include?("Ships/#{craft.craft_type.upcase}/#{craft.name}.craft")
                    = "new"
                  -else
                    - changed = new_and_changed[:changed].include?("Ships/#{craft.craft_type.upcase}/#{craft.name}.craft")
                    = changed ? "untracked" : "tracked"

                -else
                  deleted
              .history
                Number of versions:
                = craft.history_count
                -if craft.part_count && !craft.part_count.eql?(0)
                  .small
                    = craft.part_count
                    = craft.part_count.eql?(1) ? "Part" : "Parts"
                    - unless part_data.empty?
                      - unless part_data[:stock].nil?
                        |
                        = part_data[:stock] ? "Stock" : "Mod"
                      - unless part_data[:missing_parts].empty?
                        |
                        .missing= "missing #{part_data[:missing_parts].size} parts"
              
              .action_links
                .links
                  - unless craft.deleted?
                    = link_to "mcs", edit_transfer_path(craft), :remote => true
                    |
                    = link_to "d", edit_craft_path(craft), :remote => true
                  - else
                    = link_to "recover", craft_path(craft)
                
                
              -unless craft.sync[:with].blank?
                .clear
                .sync_status
                  .info= "Sync'd with #{(craft.sync[:with] - [craft.campaign_id]).size} campaigns"
          .clear

app/views/crafts/_message_form.html.haml
= form_for(craft) do |f|
  - commit_message = commit_messages[commit.to_s]
  .message_errors
  -if is_changed && commit_message.blank?
    - message = nil
  -else
    - message = commit_message
    - message ||= commit.message
  - message ||= ""
  = text_area_tag :message, message.gsub("<br>", "\r\n"), :rows => 5, :cols => 50
  .small hit tab or click outside the textbox to update
  .small (iPad users, close the keyboard)
  .updating_message.hidden
    .vblk_1
    updating commit message...
    .ajax_loader

app/views/crafts/_search_results.html.haml
- craft ||= nil
- subs ||= nil

- unless craft.nil? && subs.nil?
  - if craft.empty? && subs.blank?
    Nah, nadda.
    
  - else
    .result_count.hidden
      - results = [craft, subs].flatten.compact.sort_by{|r| r.name}
      -if craft.blank? && !subs.blank?
        = "#{results.count} subassembl#{results.count.eql?(1) ? 'y' : 'ies'} found"
      -else
        = "#{results.count} #{subs.blank? ? 'craft' : 'craft and subassembles'} found"

    - results.each do |c|
      .craft_result
        .lhs
          .name
            =link_to c.name, craft_path(c), :title => "goto craft page"
          -if c.deleted?
            .del_inf= "deleted"
          
        .location
          .right
            -if !craft.blank? && subs.blank?
              in  
            -else
              = "#{c.class.to_s.downcase} in"
              
            = link_to c.campaign.name, campaign_path(c.campaign), :title => "goto campaign page"
          .clear
          .path= c.campaign.instance.path

-else
  .result_count.hidden    
  
  Type something...
  .small= "If you really want me to list ALL of your craft, enter either *.* or *all"
        

app/views/crafts/_version_list.html.haml
- sync_targets ||= []

-if @craft && !sync_targets.blank?
  %h4= "This craft is sync'd with #{sync_targets.size} other campaign#{sync_targets.size.eql?(1) ? '' : 's'}"
  - sync_targets.each do |campaign|
    .sync_target
      .mini-flag= image_tag("/flag_for_campaign_#{campaign.id}.png")
      .path= link_to campaign.path, campaign_path(campaign)

%h3 Version History

-if @craft
  - version = @craft.history_count
  - version ||= 1
  = "#{@craft.name} has #{version} versions"
  .clear
  - changed = @craft.is_changed?
  -if changed
    .left
      .untracked Plus Untracked changes
    .left.with_margin
      = form_for(@craft, :remote => true) do |f|
        = hidden_field_tag :force_commit, true
        = f.submit "Commit (save) Now!"
  .clear
  .craft_history
    - history.each do |commit|
      .craft_info
        .craft_details
          .version= "V#{1 + (version -= 1)}"
          .value
            .hidden.sha_id= commit.sha_id
          .date= commit.date.to_formatted_s(:short)
          .restore_link
            - unless commit == history.first && !changed
              = link_to "Restore", :controller => "crafts", :action => "edit", :id => @craft, :sha_id => commit.sha_id
            -else
              Current Version

        .message
          - #onclick = "change_message(this, '#{commit.message}', #{@craft.id}, '#{commit.to_s}')"
          - #edit of past messages disabled for now as it still can cause the repo to be left in an incomplete rebase
          - message = @craft.commit_messages[commit.to_s]
          - message ||= commit.message

          .message_text
          - message.split("<br>").each do |m|
            .small= m

          .message_form{:id => "message_form_for_#{commit.to_s}"}

app/views/crafts/edit.html.haml
#craft_edit
  .grid_8.push_2

    - if @sha_id
      .help_for#craft_revert_unchanged_first_view
        %h3 Reverting a Craft
        %p
          .info= "When you revert a craft like this, that doesn't have untracked changes, the current version (in this case #{@current_version}) will be kept."

      .help_for#craft_revert_untracked_first_view
        %h3 Reverting a Craft (with untracked changes)
        %p
          .info= "When you revert a craft like this, that has untracked changes, the untracked changes will be lost."


      .help_for#craft_revert_untracked_current_commit_first_view
        %h3 Reverting a Craft (with untracked changes)
        %p
          .info= "When you revert a craft to the most recent version when it also has untracked changes, then the untracked changes will be lost."
          .info= "The craft file and version will return to #{@revert_to_version}."


      .help_for#craft_revert_page_common_first_view
        %p
          .info= "The craft <b>file</b> will be returned to how it was at the chosen version (#{@revert_to_version}).".html_safe
          .info= "The current version will remain as #{@current_version} but it will have untracked changes."
          .small= "The untracked changes are the edits to the .craft file to change it from v#{@current_version} to how it was at v#{@revert_to_version}."
        %p
          .small= "When you next launch (or manually commit) the craft, a new version (#{@current_version + 1}) with these changes will be created.  If you make edits before then, those changes will also be part of the next version."


        %p
          .info= "If you check the 'commit revert' option the untracked changes will be commited and a new version will be created straight away."
          .small="this is <b>not</b> recomended for normal use".html_safe
        %p
          %h3= "Just click Revert to go back to Version #{@revert_to_version}"
          %h4= "Then reload #{@craft.name} in KSP's #{@craft.craft_type.upcase}"

      .help_for#craft_revert_page_ending_first_view
        %p
          %h3= "Just click Revert to reset to your most recent commit"
          %h4= "Then reload #{@craft.name} in KSP's #{@craft.craft_type.upcase}"


      %h2= "Revert #{@craft.name} to Version #{@revert_to_version}?"
      .restore_details
        %h4
          .css_table
            .label Commit ID
            .value= "#{@sha_id}"
          .css_table
            .label Created on
            .value= "#{@commit.date.to_formatted_s(:short)}"
        .vblk_1
        - if @is_changed
          %h3 !!This craft has untracked changes!!
          -if @commit.to_s.eql?(@latest_commit.to_s)
            .info= "Reverting this craft will remove the untracked changes and return it to the most recent version (#{@revert_to_version})."
            .small= "The craft will be returned to version #{@revert_to_version} and there will be no untracked changes"
          -else
            .info= "You can revert to version #{@revert_to_version} but your untracked changes will be lost forever!"
            .small= "The craft file will be returned to how it was at version #{@revert_to_version}, but the craft version will remain as #{@craft.history_count} plus untracked changes until you either launch it or hit save which will create version #{@craft.history_count + 1} "

          .info
            .vblk_1
            .small
              = "If you want to track the changes before doing this revert, hit cancel and then hit the 'commit (save) now' button.  Your current changes will then be kept (as version #{@craft.history_count + 1}) and you can then revert to version #{@revert_to_version}"

        -else
          .info= "Reverting this craft will return it how it was at version #{@revert_to_version}."
          .info= "The current version (#{@craft.history_count}) will be kept, so you can always come back to it later."

        .commit_revert_info.hidden
          .vblk_1
          .info= "If you choose this option the reverted craft will automatically be commited, resulting in a new version (#{@craft.history_count + 1})."

      .vblk_1
      %h3= "Please confirm that you want to revert this craft to version #{@revert_to_version}"
      .vblk_1
      %h4 Notes from this version:
      - @commit.message.split("<br>").each do |m|
        .normal= m

      .restore_form
        = form_tag(:back, :method => :get) do
          = submit_tag "Cancel"
        = form_for(@craft) do |f|
          = hidden_field_tag :sha_id, @sha_id
          = hidden_field_tag :revert_craft, true
          = hidden_field_tag :return_to, @return_to
          = f.submit "Revert"
          - unless @commit.to_s.eql?(@latest_commit.to_s)
            .with_margin{:title => "automatically commit the reverted craft as a new version"}
              = label_tag :commit_revert, "commit revert"
              = check_box_tag :commit_revert, true, false
        .right= link_to_function "Help", "", :id => "revert_page_help_link"

      - help_type_1 = ["craft_revert_unchanged_first_view", "craft_revert_page_common_first_view", ""]
      - help_type_2 = ["craft_revert_untracked_first_view", "craft_revert_page_common_first_view", ""]
      - help_type_3 = ["craft_revert_untracked_current_commit_first_view", "craft_revert_page_ending_first_view"]

      :javascript
        show_help('craft_revert_page_intro_first_view');
      -if !@is_changed
        - help_type = help_type_1
        - auto_show = system.show_help_for?('craft_revert_unchanged')
      -if @is_changed && !@commit.to_s.eql?(@latest_commit.to_s)
        - help_type = help_type_2
        - auto_show = system.show_help_for?('craft_revert_untracked')
      -if @is_changed && @commit.to_s.eql?(@latest_commit.to_s)
        - help_type = help_type_3
        - auto_show = system.show_help_for?('craft_revert_untracked_current_commit')

      - help_type.each do |help_doc|
        :javascript
          if("#{auto_show}" == "true"){
            show_help("#{help_doc}");
          }
          $('#revert_page_help_link').bind("click", function(){show_help("#{help_doc}", {always_show: true}) })


:javascript
  $(function(){
    $('#commit_revert').prop('checked', false)
    $('#commit_revert').bind('click', function(){
      if($(this).prop('checked')==true){
        $('.commit_revert_info').show('fast');
      }else{
        $('.commit_revert_info').hide('fast');
      };
    });
  });

app/views/crafts/edit.js.haml
$("#delete_craft_dialog").remove()

$('#dialog_holder').html("#{j render :partial => "partials/delete_dialog", :locals => {:object => @craft} }");
open_delete_craft_dialog()

app/views/crafts/index.js.haml
$('#search_results').html("#{j render :partial => 'crafts/search_results', :locals => {:craft => @craft, :subs => @subs}}");
$('#result_count').html($('.result_count').html());

var h = $('#content').height() - 100
if(h > 600){h = 600}
$('#search_results').css("maxHeight", h);

app/views/crafts/show.html.haml
#craft_page
  #nav-box
    =link_to "return to campaign", campaign_path(@craft.campaign)
  .grid_10
    = hidden_field_tag :craft_id, @craft.id
    %h1= @craft.name
    %h4= "in #{@craft.campaign.name}"


  .clear
  .vblk_2
  - unless @craft.deleted?
    .grid_10.push_1
      %h2
        = link_to "Move, Copy or Sync Craft", edit_transfer_path(@craft), :remote => true
        |
        = link_to "Delete Craft", edit_craft_path(@craft), :remote => true 
        = #link_to_function "mo", "delete_craft_dialog()"
      .vblk_1
      

      -if @parts.stock?
        %h4= "#{@craft.name} is 100% Stock"
      -else
        %h4= "#{@craft.name} uses #{@parts.mods.size} mod#{@parts.mods.size.eql?(1) ? '' : 's'};"
        = @parts.mods.sort.join(", ")

      .link= link_to_function "show parts", "$('.parts_list').is(':visible') ? $(this).html('show parts') : $(this).html('hide parts'); $('.parts_list').toggle('slow'); "

      .clear
      .parts_list
        - @part_for_list.each do |parts_group|
          .grid_5.alpha
            - parts_group.each do |part|
              - next if  part.nil?
              - mod = " #{part[1].first[:mod].sub('Squad', 'Stock')}" unless @parts.stock?
              - s = "#{part[1].count}#{mod} - #{part[0]}"
              .part
                %b= s
                .details
                  .info= link_to "#{part[1].first[:dir]}", {:action => :show, :controller => :crafts, :id => @craft.id, :open_part_folder => "#{part[1].first[:dir]}"}, :remote => true
                  .info= "#{part[1].first[:resources].join(', ')}"

      .clear
      .vblk_1

      -if @parts.missing?
        .missing_parts
          %h4= "#{@craft.name} is missing these parts"
          - @parts.missing.in_groups(3) do |group|
            .grid_3
              - group.each do |part|
                .small= part
        .clear
        .vblk_1
        .clear

      #history_list
        %h3 Version History
        Loading craft History
        .ajax_loader

    :javascript
      $(function(){craft_show_actions()});
                 

  -else
    .grid_6.push_3
      .restore_craft
        %h2 This Craft has been deleted!
        %h4 All is lost, will we ever see it again?
        %h4 Oh wait, just click Recover it!

        .restore_form
          = form_tag(:back, :method => :get) do
            = submit_tag "Cancel"
          = form_for(@craft) do |f|
            = hidden_field_tag :recover_deleted, true
            = f.submit "Recover It!"

app/views/crafts/show.js.haml
if("#{@background_process}" != "waiting"){
$('#history_list').html("#{j render :partial => 'crafts/version_list', :locals => {:history => @history, :sync_targets => @sync_targets} }");
};