config/routes.rb
Jebretary::Application.routes.draw do
  get "welcome/index"
  get "welcome/edit"
  post "welcome/update"
  match "instances/:id/update" => "instances#update"

  resources :subassemblies
  resources :launch
  resources :transfer
  resources :messages
  
  resources :campaigns do
    resources :saves
  end
  resources :saves  
  resources :crafts
  resources :instances

  match "settings" => "welcome#settings"  
  match "new_version_info" => "welcome#new_version_info"
  match "reset_cache" => "application#cache_reset"

  root :to => 'welcome#index'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  attr_accessible :full_path, :part_db_checksum, :part_update_required, :use_x64_exe

  validates :full_path, :presence => true
  has_many :campaigns, :dependent => :destroy
  has_many :craft, :through => :campaigns

  def path
    p = JSON.parse(self.full_path)
    File.join(p)
  end

  def name
    File.split(self.path).last
  end
    
  def exists?
    File.exists? self.path
  end

  def x64_available? 
    File.exists? File.join(self.path, "KSP_x64.exe")
  end

  def discover_campaigns
    ignored = ['.', '..', 'training', 'scenarios']   
    save_dir = File.join(self.path, "saves")
    dirs = Dir.entries(save_dir).select{|entry| 
      File.directory? File.join(save_dir,entry) and !ignored.include?(entry)
    }
  end

  def prepare_campaigns
    return [] unless self.exists?
    existing_campaigns = discover_campaigns
    new_campaigns = []
    known_campaign_names = self.campaigns.map{|c| c.name}
    existing_campaigns.each do |camp|
      next if known_campaign_names.include?(camp)
      new_campaigns << Campaign.create!(:name => camp, :instance_id => self.id)
    end
    [existing_campaigns, new_campaigns]
  end

  #return the .craft files found in VAB and SPH
  def identify_craft_in campaign_name
    dir = File.join(self.path, "saves", campaign_name, "Ships")
    Dir.chdir(dir)
    {
      :vab => Dir.glob("VAB/*.craft").map{|craft| craft.gsub("VAB/", "")}, 
      :sph => Dir.glob("SPH/*.craft").map{|craft| craft.gsub("SPH/", "")}
    }
  end

  #return the parts info for this instance.  Either from an already loaded instance of @parts, or loaded from the .partsDB file (if present)
  #or if neither @parts or the .partsDB file are present a fresh parts map is made (and saved to the .partsDB file).
  #Each time System is startd up (ie each time Jebretary is launched) the partsDB file is reset and rebuilt (this is done by System)
  def parts
    if defined?(@parts) && !@parts.nil?
      return @parts 
    else
      if File.exists?(File.join([self.path, "jebretary.partsDB"]))
        return @parts = PartParser.new(self.path, :source => :from_file)
      else
        @parts = PartParser.new(self.path, :source => :game_folder, :write_to_file => true)

        #we need to know if there has been a change in the installed parts since the last time Jebretary was launched.
        #therefore a checksum of the partsDB is stored and if it differs from the current checksum then part_update_required is set to true
        #this will be used to prompt the user about re-processing all craft in this instance for thier parts.
        pdc = generate_part_db_checksum
        if self.part_db_checksum != pdc
          self.part_update_required = true unless self.part_db_checksum.nil?
          self.part_db_checksum = pdc          
          self.save
        end
        return @parts
      end
    end  
  end

  def generate_part_db_checksum
    path = File.join([self.path, "jebretary.partsDB"])    
    File.exists?(path) ? Digest::SHA256.file(path).hexdigest : nil
  end

  def reset_parts_db
    path = File.join([self.path, "jebretary.partsDB"])
    File.delete(path) if File.exists?(path)
  end


end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController

  respond_to :html, :js
  before_filter :assign_instance, :only => [:edit, :destroy]


  def index
    @instances = Instance.all
  end

  def create
    #/home/sujimichi/Share/KSPv0.19.1
    #r:\\Games\\KSPv0.19.1
    #params[:full_path] = "r:\\Games\\KSPv0.19.1"
    #params[:full_path] = "/home/sujimichi/Share/KSPv0.19.1"

    full_path = params[:full_path]
    if full_path.include?("/")
      full_path = full_path.split("/")
    elsif full_path.include?("\\")
      full_path = full_path.split("\\")
    else
      full_path = "error"
    end

    @instance = Instance.new(:full_path => full_path.to_json)
    

    begin
      files = Dir.open(File.join(full_path)).to_a
      raise "nothing found" if files.blank?
    rescue
      @instance.errors.add(:base, "unable to open directory '#{params[:full_path]}'")
    end
    @instance.errors.add(:base, "couldn't locate KSP.exe") if !files.blank? && !(files.include?("KSP.exe") || files.include?("KSP_x64.exe") )


    respond_with(@instance) do |f|      
      if @instance.errors.empty?
        @instance.use_x64_exe = true if @instance.x64_available?
        @instance.save
        
        Task.create(:action => ["generate_part_db_for", @instance.id]) 
        f.js { }
      else
        f.html { render :action => "new", :status => 422 }
      end
    end
  end

  def show
    respond_to do |f|           
      f.html{
        @instance = Instance.find(params[:id])
        unless @instance.campaigns.empty?
          @instance.prepare_campaigns
          @campaigns = @instance.reload.campaigns
          @campaigns.select{|c| c.exists? }.each{|c| c.set_flag}
        end
      }
      f.js  {
        ensure_no_db_lock do 
          @instance = Instance.find(params[:id])
          @campaigns = @instance.campaigns.select{|c| c.exists?}
        end      
      }
    end
  end

  def update

    @instance = Instance.find(params[:id])

    if @instance.use_x64_exe
      #switching to x32
      if File.exists? File.join(@instance.path, "KSP.exe")
        @instance.use_x64_exe = false
        notice = "When you next launch KSP from Jebretary it will start in 32 bit mode"
      else
        alert = "32 bit exe could not be found in this instance. Sorry, I can only launch this as x64"
      end
    else
      #switching to x64
      if File.exists? File.join(@instance.path, "KSP_x64.exe")
        @instance.use_x64_exe = true
        notice = "When you next launch KSP from Jebretary it will start in 64 bit mode"
      else
        alert = "64 bit exe could not be found in this instance. Sorry, I can only launch this as x32"
      end      
    end
    @instance.save

    redirect_to :back, :notice => notice, :alert => alert
    
  end


  def edit
    respond_to do |f| 
      f.js{ 
        if params[:rescan]
          @instance.reset_parts_db
          Task.create(:action => ["generate_part_db_for", @instance.id])           
        end
        Task.create(:action => ["update_part_data_for", @instance.id]) 
      }
    end
  end

  def destroy
    @instance.destroy
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end  

  protected

  def action_when_locked status
    unless status.blank?
      data = JSON.parse(status) unless status.blank?
      @background_process = data[params[:id]] if data[params[:id]]
    end
    @flags = Dir.entries(File.join([Rails.root,"public"])).select{|f| f.include?("flag_for_campaign")}.map{|f| f.sub("flag_for_campaign_","").sub(".png","").to_i}.to_json
    @background_process ||= "waiting"
  end

  def assign_instance
    @instance = Instance.find(params[:id])
  end
end

app/views/instances/_form.html.haml
= form_for(instance) do |f|
  - unless instance.errors.empty?
    %h2 I could not continue
    .form_errors
      = instance.errors.full_messages.join
    .info You need to enter a full file path to a directory where KSP is installed, for example;
    .info c:\games\ksp_win

  = text_field_tag :full_path
  #detected_instances
  = content_for :information
  .clear
  = f.submit("OK")

app/views/instances/index.html.haml
#standard_page
  #nav-box
    =link_to "home", root_path
  %h1 All Instances
  .vblk_1
  .grid_11.push_1    
    .small.info If you are no longer using a particular instance of KSP it is a good idea to stop tracking it
    .small.info Removing an instance will not effect the files in KSP or the version history, you can always re-add it to pick up where you left off  
  .clear
  
  .vblk_2
  .grid_8.push_2
    - @instances.each do |instance|
      .instance
        .left
          %h3= link_to instance.path, instance_path(instance)
        .right
          = link_to 'Stop Tracking', instance, :method => :delete, :data => { :confirm => 'This will remove the reference to this install of KSP and all campaign and craft data.  (It will not effect your actual KSP install).  Are you sure you want to delete this?' }
        .clear
        - cur_mode = instance.use_x64_exe? ? "64" : "32"
        - alt_mode = {"64" => "32", "32" => "64"}
        = "this instance will be launched in #{cur_mode} bit mode"
        - if instance.x64_available?
          |
          = link_to "change to #{alt_mode[cur_mode]} bit", :controller => :instances, :action => :update, :id => instance.id, :method => :put, :switch_launch_mode => true
          


        -unless instance.exists?
          %h4= "This Instance can not be found and will be ignored"

app/views/instances/new.html.haml
#new_instance_page
  #nav-box
    = link_to "Cancel", :back
  .clear
  .grid_6.push_3
    = render('instances/form', :instance => @instance)
    .clear

app/views/instances/show.html.haml
#instance_page
  %h2= File.join(JSON.parse(@instance.full_path))
  = hidden_field_tag :instance_id, @instance.id
  #nav-box
    =link_to "return home", root_path

  = hidden_field_tag(:available_flags, @flags)
  - content_for :title_bar do 
    = render "launch/instance", :instance => @instance

  -if system.show_help_for?("instance_page_for_#{@instance.id}")
    .help_for#instance_page_first_view.hidden
      %h3= "I've finished detecting campaigns and craft in this install of KSP"
      .info Click on a campaign to view its craft
      .info.small Craft may not yet have their part info available.  I will gradually work through your craft and scan them in the background.
      .info.small Craft that have been scanned will be color coded (blue for stock, green for modded).
      .info.small= "If you want me to scan all your craft right now, click the 'Re-scan parts and craft' link below."
      .vblk_1

  -if system.show_help_for?("updating_several_craft_#{@instance.id}")
    .help_for#updating_several_craft.hidden
      .vblk_1
      %h3 The System is now adding your craft to version control...
      .info The system is doing an initial scan of the saves folder for this install of KSP.
      .info This will add your existing craft to the repository and the database.
      .info If you have quite a few craft (100+) this may take a minute or two.
      .vblk_1
      .info It's best to just wait for this initial scan to complete before clicking on a campaign.
      .vblk_1
      
  - if @instance.part_update_required?
    #part_update_required_dialog.hidden
      = render "errors/part_update_required", :instance => @instance

          
  #temp_holder

  #campaigns_list
    .loading
      .ajax_loader
      Loading Stuff....
  .clear
  
  .grid_8.push_2.rescan_link.hidden.centered
    %h2= link_to "Re-scan parts and craft", edit_instance_path(:id => @instance.id, :rescan => true), :method => :get, :remote => true, :onclick => "rescanning_notification()"
    .small= "(click this if you have changed/updated your mods/parts)"
    
  #rescan_notify_dialog.hidden
    %h4= "The craft in this instance #{@instance.path} will have their parts re-scanned shortly"
    %h4= "During the rescan changes to craft and saves will not be tracked, but you can carry on playing KSP and using Jebretary"
    .right
      .vblk_1
      = button_to_function "OK", "$('#rescan_notify_dialog').dialog('close');"
      
     

:javascript
  $(function(){
    poll_for_updated_instance();
  });
  
  function rescanning_notification(){
    $('#rescan_notify_dialog').dialog({ height: 'auto', width: '800px', position: ["center", 100], title: "Part Info Rescan" })
  };

app/views/instances/show.js.haml
if($('#campaigns_list').find(".loading").html() != undefined){
$('#campaigns_list').html("")
}

if("#{@background_process}" != "waiting"){
$('#temp_holder').html("#{j render :partial => 'campaigns/list', :locals => {:instance => @instance, :campaigns => @campaigns, :background_process => @background_process} }");
};

poll_for_updated_instance();