config/routes.rb
Jebretary::Application.routes.draw do
  get "welcome/index"
  get "welcome/edit"
  post "welcome/update"
  match "instances/:id/update" => "instances#update"

  resources :subassemblies
  resources :launch
  resources :transfer
  resources :messages
  
  resources :campaigns do
    resources :saves
  end
  resources :saves  
  resources :crafts
  resources :instances

  match "settings" => "welcome#settings"  
  match "new_version_info" => "welcome#new_version_info"
  match "reset_cache" => "application#cache_reset"

  root :to => 'welcome#index'

end

app/controllers/saves_controller.rb
class SavesController < ApplicationController
   
  respond_to :js, :html

  def index
    @campaign = Campaign.find(params[:campaign_id])
  end

  def edit
    @campaign = Campaign.find(params[:id])
    respond_with(@campaign) do |f|
      f.js{
        @save_type = params[:save_type]
        
        path = File.join([@campaign.path, "#{params[:save_type]}.sfs"])
        @commit = @campaign.repo.get_commit(:for => path, :sha_id => params[:sha_id]) #attempt to fast find commit 
        #@commit ||= @campaign.repo.gcommit(params[:sha_id]) #fallback if above didn't work

        @versions_ago = params[:versions_ago].to_i if params[:versions_ago]
        @versions_ago ||= @campaign.save_history(:limit => 5)[@save_type.to_sym].map{|c| c.to_s}.index(@commit.to_s)

        if params[:commit_message]
          @message = @commit.message
          @commit_messages = @campaign.commit_messages
          stored_message = @commit_messages[@commit.to_s]
          @message = stored_message if stored_message
        end
      }
    end    
  end

  def update
    campaign = Campaign.find(params[:id])
    if params[:sha_id]
      path = File.join([campaign.path, "#{params[:save_type]}.sfs"])
      commit = campaign.repo.get_commit(:for => path, :sha_id => params[:sha_id]) #attempt to fast find commit 
      commit ||= campaign.repo.gcommit(params[:sha_id]) #fallback if above didn't work
      
      campaign.revert_save params[:save_type], commit, :commit => true     
      note = "Your #{params[:save_type]}.sfs file has been reverted"
    end
    
    if params[:revert_as_quicksave]
      campaign.persistent_to_quicksave 
      if params[:sha_id]
        note = "Your persistent.sfs file has been reverted and the quicksave has been replaced with it"
      else
        note = "Your quicksave file has been replaced with the persistent file"
      end
    end
    if params[:save_type].eql?("quicksave") || params[:revert_as_quicksave]
      note << "</br>Hold F9 in KSP to load it"
    end
    campaign.update_attributes(:persistence_checksum => nil)
    redirect_to :back, :notice => note.html_safe
  end
end

app/views/saves/_replace_quicksave_with_persistent.haml
%h3= "Set Persistent as Quicksave"
= "Click ok to replace your quicksave with the current persistent"

.vblk_1
.revert_form
  = form_tag("/saves/#{campaign.id}", :method => "put") do |f|
    = hidden_field_tag :save_type, save_type
    = hidden_field_tag :revert_as_quicksave, true

    .left
      = submit_tag("OK")
  .right= button_to_function "Cancel", "$('#edit_save_holder').dialog( 'close' );"

app/views/saves/_revert_save.html.haml
%h3= "Revert #{save_type} for #{campaign.name}"
-if versions_ago.eql?(1)
  = "Click ok to revert your #{save_type} to the previous version"
-else
  = "Click ok to revert your #{save_type} to #{versions_ago} versions ago"
- date = Time.now.utc_offset.seconds.ago(commit.date)
.small= "(made #{time_ago(date)} ago)"

.vblk_1
.small= "check 'revert as quicksave' so you can load the persistent save with f9" if save_type.eql?("persistent")
.revert_form
  = form_tag("/saves/#{campaign.id}", :method => "put") do |f|
    = hidden_field_tag :sha_id, commit.to_s
    = hidden_field_tag :save_type, save_type
    -if save_type.eql?("persistent")
      = label_tag  :revert_as_quicksave, "revert as quicksave"
      = check_box_tag :revert_as_quicksave, true
      .vblk_1

    .left
      = submit_tag("OK")
  .right= button_to_function "Cancel", "$('#edit_save_holder').dialog( 'close' );"

app/views/saves/_short_list.html.haml
- save_type = save_type.to_sym
-unless saves[save_type].blank?
  - latest = saves[save_type].first
  -if has_change
    .new_save_detected= "New #{save_type.capitalize} detected, hang on while I commit it..."
  - saves[save_type][0..4].each_with_index do |qsave, index|
    - message = qsave.message
    - message = campaign_commit_messages[qsave.to_s] unless campaign_commit_messages[qsave.to_s].blank?
    .small.small
      .left= qsave.date.to_formatted_s(:short)
      .left.with_margin= "#{time_ago(qsave.date)} ago"
      .right
        - unless index.eql?(0)
          = link_to("restore", edit_save_path(:id => campaign.id, :sha_id => qsave.to_s, :save_type => save_type), :remote => true)
        -else
          = "current #{save_type}"
          -if save_type.eql?(:persistent)
            .small= link_to("set as quicksave", edit_save_path(:id => campaign.id, :sha_id => qsave.to_s, :save_type => save_type, :set_as_quicksave => true), :remote => true)
      .clear
      .left
        - unless message.eql?("updated #{save_type}.sfs")
          .left
            - message.split("<br>").each do |m|
              .small= m
      .clear
  - unless has_change
    = link_to("add notes about current #{save_type}", edit_message_path(:id => campaign.id, :sha_id => saves[save_type].first.to_s, :save_type => save_type, :commit_message => true), :remote => true)
- else
  - if save_type.eql?(:quicksave)
    .small= "No quicksave file found."
    .small= "When you make a quicksave it will show up here"

app/views/saves/edit.js.haml
if("#{params[:set_as_quicksave]}"){
$('#edit_save_holder').html("#{j render :partial => 'saves/replace_quicksave_with_persistent', :locals => {:campaign => @campaign, :save_type => @save_type, :commit => @commit, :versions_ago => @versions_ago} }")
}else{
$('#edit_save_holder').html("#{j render :partial => 'saves/revert_save', :locals => {:campaign => @campaign, :save_type => @save_type, :commit => @commit, :versions_ago => @versions_ago} }")
};

$('#edit_save_holder').dialog();
$('#edit_save_holder').dialog( "close" );
$('#edit_save_holder').dialog({ height: 'auto', width: 'auto', position: ["center", 150] });

app/views/saves/index.html.haml
#campaign_save_index
  #nav-box
    =link_to "back to campaign", campaign_path(@campaign)
  #edit_save_holder.hidden
  .grid_12
    %h2= "Saves for #{@campaign.name}"
    .small= "Note: this page does not auto update, whack f5 to reload it"
    .small= "touch screen users, tap a save in the list to show the restore link"

  - saves = @campaign.save_history
  - save_types = [:quicksave, :persistent]
  .clear
  .vblk_1
  .grid_12
    - save_types.each_with_index do |save_type, index|
      -unless saves[save_type].blank?
        - klass = 'grid_6 alpha'
        -# klass << " push_1" if index.eql?(1)
        .save_list{:class => klass}
          %h3= save_type
          - latest = saves[save_type].first
          - current_version = saves[save_type].size + 1
          - v = current_version 
          - saves[save_type].each_with_index do |qsave, index|
            .save{:onmouseover => "show_restore_link_for(this)"}
              - v = v -=1
              .left.label= "V#{v}"
              .left.with_margin= qsave.date.to_formatted_s(:short)
              .left.with_margin.small= "#{time_ago(qsave.date)} ago"
              .right
                - unless index.eql?(0)
                  .restore_link.hidden= link_to("restore to V#{v}", edit_save_path(:id => @campaign.id, :sha_id => qsave.to_s, :save_type => save_type, :versions_ago => (current_version-v-1)), :remote => true)
                -else
                  = "current #{save_type}"
                  -if save_type.eql?(:persistent)
                    .small= link_to("set as quicksave", edit_save_path(:id => @campaign.id, :sha_id => qsave.to_s, :save_type => save_type, :set_as_quicksave => true), :remote => true)
              .clear
              .left
                .small= qsave.message unless qsave.message.eql?("updated #{save_type}.sfs")
              .clear
      - else
        %h4= "Could not find a #{save_type}.sfs file"